sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: 123456
  alioss:
    endpoint: oss-cn-beijing.aliyuncs.com
    access-key-id: ${OSS_ACCESS_KEY_ID}
    access-key-secret: ${OSS_ACCESS_KEY_SECRET}
    bucket-name: javacan-ai
  redis:
    host: localhost
    port: 6379
    password: 123456
    database: 10
  wechat:
    appid: ${WECHAT_APPID}
    secret: ${WECHAT_SECRET}
    mchid: 1561414331
    mchSerialNo: 4B3B3DC35414AD50B1B755BAF8DE9CC7CF407606
    privateKeyFilePath: C:\Users\Zch\Desktop\wxb0e3dbf6ee2038f7.txt
    apiV3Key: CZBK51236435wxpay435434323FFDuv3
    weChatPayCertFilePath: C:\Users\Zch\Desktop\wxb0e3dbf6ee2038f7.txt
    notifyUrl: https://6770c9fe.r40.cpolar.top//notify/paySuccess
    refundNotifyUrl: https://6770c9fe.r40.cpolar.top//notify/refundSuccess


